// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt56DlxzZX1M0_L5sNpSyLNwEh86crARA',
    appId: '1:992660960797:web:b61f0d30babc5a18ddf8f4',
    messagingSenderId: '992660960797',
    projectId: 'flowru-mobile-a05b7',
    authDomain: 'flowru-mobile-a05b7.firebaseapp.com',
    storageBucket: 'flowru-mobile-a05b7.firebasestorage.app',
    measurementId: 'G-ZP0S9T4849',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIQcETKuzcOQ5JUV6mhLTz4ihldKDysE',
    appId: '1:992660960797:android:963f15ec5b1a235cddf8f4',
    messagingSenderId: '992660960797',
    projectId: 'flowru-mobile-a05b7',
    storageBucket: 'flowru-mobile-a05b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3U9idkt-yQaDaxpuU_1SYLXMNb_Uw18',
    appId: '1:992660960797:ios:56d7ce06553aec2eddf8f4',
    messagingSenderId: '992660960797',
    projectId: 'flowru-mobile-a05b7',
    storageBucket: 'flowru-mobile-a05b7.firebasestorage.app',
    iosBundleId: 'com.flowru.staff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3U9idkt-yQaDaxpuU_1SYLXMNb_Uw18',
    appId: '1:992660960797:ios:27302134b3ebb751ddf8f4',
    messagingSenderId: '992660960797',
    projectId: 'flowru-mobile-a05b7',
    storageBucket: 'flowru-mobile-a05b7.firebasestorage.app',
    iosBundleId: 'com.example.flowruStaff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt56DlxzZX1M0_L5sNpSyLNwEh86crARA',
    appId: '1:992660960797:web:d49302a5a502832dddf8f4',
    messagingSenderId: '992660960797',
    projectId: 'flowru-mobile-a05b7',
    authDomain: 'flowru-mobile-a05b7.firebaseapp.com',
    storageBucket: 'flowru-mobile-a05b7.firebasestorage.app',
    measurementId: 'G-8KBBKXBTJ4',
  );
}
